name: Google-Play-Android-Distribution

on:
  # Triggers the workflow on push or pull request events but only for the study-1 branch
  push:
    branches: [study-1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Prepare ionic build
        uses: coturiv/setup-ionic@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run ionic build
        run: |
          npm install npm@8 -g
          npm ci
          ionic cap build android --no-interactive --no-open --confirm --prod

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.0.3
        with:
          ndk-version: r21d

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android keystore
        working-directory: ./android
        run: |
          echo $ANDROID_KEYSTORE | base64 -di > simport.keystore
          ls -lah
        env:
          ANDROID_KEYSTORE: ${{ secrets.GOOGLE_PLAY_ANDROID_KEYSTORE }}

      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: ./android/app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Build with Gradle
        working-directory: ./android
        run: ./gradlew app:bundleRelease
        env:
          ANDROID_PATH_TO_KEYSTORE: '../simport.keystore'
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_PASSWORD }}

      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: aab-artifact
          path: android/app/build/outputs/bundle/release/app-release.aab

  deploy-android:
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: aab-artifact
          path: ./

      - name: Upload on play store
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: de.ifgi.simport.learning
          releaseFiles: app-release.aab
          track: internal
